export enum LeadValidationFormField {
  FirstName = 'firstName',
  LastName = 'lastName',
  Email = 'email',
  LinkedInLink = 'linkedinLink',
  JobTitle = 'jobTitle',
  JobFunction = 'jobFunction',
  JobLevel = 'jobLevel',
  CompanyName = 'companyName',
  Domain = 'domain',
  Industry = 'industry',
  EmployeeSizeDistinct = 'distinctEmployeeSize',
  RevenueSizeDistinct = 'distinctRevenueSize',
  RFPEmployeeSizeSize = 'rfpEmployeeSize',
  RFPRevenueSize = 'rfpRevenueSize',
  CountryCode = 'countryCode',
  Phone = 'phone',
  StreetAddress = 'streetAddress',
  City = 'city',
  State = 'state',
  Country = 'country',
  PostalCode = 'postalCode',
  OptIn = 'optIn',
  DoubleOptIn = 'doubleOptIn',
  Asset1DownloadDate = 'asset1DownloadDate',
  Asset2DownloadDate = 'asset2DownloadDate',
}
