export enum LineItemSections {
  MarketerDetails = 'marketerDetails',
  CampaignDetails = 'campaignDetails',
  ClientDetails = 'clientDetails',
  LineItemDetails = 'lineItemDetails',
  SupplierDetails = 'supplierDetails',
  Assets = 'assets',
  Goals = 'goals',
  Delivery = 'delivery',
  DeliveryFileUpload = 'deliveryFileUpload',
  JobTitleCheck = 'jobTitleCheck',
  JobTitleDetails = 'jobTitleDetails',
  TALFileUpload = 'TALFileUpload',
  SuppressionFileUpload = 'suppressionFileUpload',
  Pacing = 'pacingHeader',
  CustomQuestions = 'customQuestionsDetails',
  Contact = 'contact',
  Firmographics = 'firmographics',
  CompanySizeCount = 'companySizeCount',
  CompanySizeRevenue = 'companySizeRevenue',
  Geography = 'geography',
  Intent = 'intent',
  Technographics = 'technographics',
  AdditionalInstructions = 'additionalInstruction',
  Collaborators = 'collaborators',
}
