export enum LineItemPicklistMappings {
  Products = 'product',
  DeliveryDays = 'delivery-days',
  DeliveryMethods = 'delivery-methods',
  Pacing = 'pacing',
  PacingSchedules = 'pacing-schedule',
  JobFunctions = 'job-function',
  JobLevels = 'job-level',
  Industries = 'industry',
  CompanySizesByEmployeeCount = 'company-size-employee-count',
  CompanySizesByRevenue = 'company-size-revenue',
  Regions = 'regions',
  Countries = 'country',
  ValidationTemplates = 'validation-templates',
}
