export enum RemoveNotRequiredKeys {
  CampaignIdNumber = 'campaignIdNumber',
  LineItemId = 'id',
  ClientIdNumber = 'clientIdNumber',
  DeliveryTemplate = 'deliveryTemplate',
  CustomerSuccessManager = 'customerSuccessManager',
  CustomerSuccessRep = 'customerSuccessRep',
  OperationsManager = 'operationsManager',
  OperationsTeamLeader = 'operationsTeamLeader',
  QaManager = 'qaManager',
  QaTeamLead = 'qaTeamLead',
  DeliveryManager = 'deliveryManager',
  MisTeamLeader = 'misTeamLeader',
  CcdTeamLeader = 'ccdTeamLeader',
  JobTitleListUpload = 'jobTitleFileDetails',
  TargetAccountListTALUpload = 'talFileDetails',
  SuppressionListUpload = 'suppressionFileDetails',
  IntentKeywordsList = 'intentKeywordFileDetails',
  TechnologyListUpload = 'technologyFileDetails',
}
