export enum OptionsKeys {
  Clients = 'clients',
  Marketers = 'marketers',
  Suppliers = 'suppliers',
  Campaigns = 'campaigns',
  CampaignGoals = 'campaignGoals',

  InvoicingTerm = 'invoicingTerm',
  PaymentTerm = 'paymentTerm',
  DeliveryMethod = 'deliveryMethod',

  Products = 'products',
  Pacing = 'pacing',
  PacingSchedules = 'pacingSchedules',
  DeliveryDays = 'deliveryDays',
  CompanySizesEmployeeCount = 'companySizesEmployeeCount',
  JobFunctions = 'JobFunctions',
  JobLevels = 'JobLevels',
  Industries = 'Industries',
  CompanySizesRevenue = 'companySizesRevenue',
  GeographyByRegion = 'geographyByRegion',
  GeographyByCountry = 'geographyByCountry',

  CustomerSuccessManager = 'customerSuccessManager',
  CustomerSuccessRep = 'customerSuccessRep',
  OperationsManager = 'operationsManager',
  QAManager = 'qaManager',
  QATeamLeader = 'qaTeamLeader',
  DeliveryManager = 'deliveryManager',
  MISTeamLeader = 'misTeamLeader',
  CCDTeamLeader = 'ccdTeamLeader',
  AssignedTo = 'assignedTo',

  DataType = 'dataType',
  ValidationTemplates = 'validationTemplates',
}
