import Icon from '@ant-design/icons';
export { Icon };

// Only the 66 icons actually used in the codebase
export {
  ApiOutlined,
  ArrowLeftOutlined,
  ArrowRightOutlined,
  AudioOutlined,
  CalendarOutlined,
  CaretDownFilled,
  CaretDownOutlined,
  CaretUpFilled,
  CaretUpOutlined,
  CheckCircleFilled,
  CheckCircleOutlined,
  CheckOutlined,
  ClockCircleOutlined,
  CloseCircleOutlined,
  CloseCircleTwoTone,
  CloseOutlined,
  CloudUploadOutlined,
  CopyOutlined,
  DatabaseOutlined,
  DeleteOutlined,
  DollarCircleOutlined,
  DoubleRightOutlined,
  DownOutlined,
  DownloadOutlined,
  EditOutlined,
  ExclamationCircleFilled,
  ExclamationCircleOutlined,
  EyeOutlined,
  FallOutlined,
  FileDoneOutlined,
  FileImageOutlined,
  FileOutlined,
  FileTextOutlined,
  FilterFilled,
  FilterOutlined,
  FolderViewOutlined,
  FormOutlined,
  InboxOutlined,
  InfoCircleFilled,
  InfoCircleOutlined,
  LeftOutlined,
  LoadingOutlined,
  LogoutOutlined,
  MessageOutlined,
  MinusCircleOutlined,
  MoreOutlined,
  PaperClipOutlined,
  PauseOutlined,
  PlayCircleOutlined,
  PlusCircleOutlined,
  PlusOutlined,
  ReloadOutlined,
  RightOutlined,
  RiseOutlined,
  SaveOutlined,
  SearchOutlined,
  SendOutlined,
  SwapRightOutlined,
  SyncOutlined,
  ThunderboltOutlined,
  UndoOutlined,
  UpOutlined,
  UploadOutlined,
  UserAddOutlined,
  UserOutlined,
  WarningOutlined,
} from '@ant-design/icons';

export { BlueTickIcon } from './svgs/blue-tick';
