import { LineItemFields, LineItemSteps } from '../enums';

export const UnsavedLineItemTargetFields = {
  [LineItemSteps.BasicDetails]: [
    LineItemFields.LineItemName,
    LineItemFields.NeedLandingPageBuilt,
    LineItemFields.PONumber,
    LineItemFields.ProofLinks,
  ],
  [LineItemSteps.Goals]: [
    LineItemFields.Product,
    LineItemFields.DoubleOptIn,
    LineItemFields.TargetLeadGoal,
    LineItemFields.IsValueAddedLineItem,
    LineItemFields.TargetCostPerLead,
    LineItemFields.LineItemTargetStartDate,
    LineItemFields.LineItemTargetEndDate,
    LineItemFields.LeadCapPerDomain,
  ],
  [LineItemSteps.DeliveryAndPacing]: [
    LineItemFields.TargetDeliveryStartDate,
    LineItemFields.DeliveryMethod,
    LineItemFields.IntegrateConverterID,
    LineItemFields.LeadDeliveryTemplateFileIncluded,
    LineItemFields.DeliveryTemplate,
    LineItemFields.DeliveryDays,
    LineItemFields.Pacing,
    LineItemFields.PacingChartLink,
  ],
  [LineItemSteps.CustomQuestions]: [
    LineItemFields.HasCustomQuestions,
    LineItemFields.CustomQuestionInstructions,
    LineItemFields.CustomQuestions,
  ],
  [LineItemSteps.Targeting]: [
    LineItemFields.JobFunctions,
    LineItemFields.JobLevels,
    LineItemFields.JobTitles,
    LineItemFields.JobTitleListIncluded,
    LineItemFields.JobTitleListUploadId,
    LineItemFields.Industries,
    LineItemFields.CompanySizesEmployeeCount,
    LineItemFields.CompanySizesRevenue,
    LineItemFields.TargetAccountListTALIncluded,
    LineItemFields.TargetAccountListTALUploadId,
    LineItemFields.SuppressionListIncluded,
    LineItemFields.SuppressionListUploadId,
    LineItemFields.GeographyByRegion,
    LineItemFields.GeographyByCountry,
    LineItemFields.IntentTargeting,
    LineItemFields.IntentKeywordsUploadId,
    LineItemFields.TechnographicTargeting,
    LineItemFields.TechnologyUploadId,
    LineItemFields.AdditionalInstructions,
  ],
};
