import { LineItemFields } from '../enums';

export const UnsavedLineItemSourceFields = [
  LineItemFields.LineItemName,
  LineItemFields.LineItemTargetStartDate,
  LineItemFields.LineItemTargetEndDate,
  LineItemFields.TargetCostPerLead,
  LineItemFields.PONumber,
  LineItemFields.NeedLandingPageBuilt,
  LineItemFields.ProofLinks,
  LineItemFields.PacingChartLink,
  LineItemFields.TargetDeliveryStartDate,
  LineItemFields.IntegrateConverterID,
  LineItemFields.LeadDeliveryTemplateFileIncluded,
  LineItemFields.CustomQuestionInstructions,
  LineItemFields.CustomQuestions,
  LineItemFields.HasCustomQuestions,
  LineItemFields.DoubleOptIn,
  LineItemFields.TargetLeadGoal,
  LineItemFields.IsValueAddedLineItem,
  LineItemFields.LeadCapPerDomain,
  LineItemFields.AdditionalInstructions,
  LineItemFields.JobTitleListIncluded,
  LineItemFields.JobTitles,
  LineItemFields.TargetAccountListTALIncluded,
  LineItemFields.SuppressionListIncluded,
  LineItemFields.IntentTargeting,
  LineItemFields.TechnographicTargeting,
];
