export enum ViewCampaignPermissions {
  MarketerId = 'Campaign.VIEW.marketerId',
  Marketer = 'Campaign.VIEW.marketer',
  CampaignName = 'Campaign.VIEW.campaignName',
  CampaignId = 'Campaign.VIEW.campaignId',
  IoNumber = 'Campaign.VIEW.ioNumber',
  UploadIoFile = 'Campaign.VIEW.ioFileId',
  CampaignDescription = 'Campaign.VIEW.campaignDescription',
  SalesforceOpportunityId = 'Campaign.VIEW.salesforceOpportunityId',
  SalesforceOpportunityName = 'Campaign.VIEW.salesforceOpportunityName',
  SalesforceOpportunityLink = 'Campaign.VIEW.salesforceOpportunityLink',
  BillingSystemReferenceId = 'Campaign.VIEW.billingSystemReferenceId',
  OpportunityCloseDate = 'Campaign.VIEW.opportunityCloseDate',
  RetainerContract = 'Campaign.VIEW.retainerContract',
  BookedRevenue = 'Campaign.VIEW.bookedRevenue',
  CampaignGoals = 'Campaign.VIEW.campaignGoals',
  GoalDescription = 'Campaign.VIEW.goalDescription',
  TargetEndDate = 'Campaign.VIEW.targetEndDate',
  TargetStartDate = 'Campaign.VIEW.targetStartDate',
  InvoicingTerm = 'Campaign.VIEW.invoicingTerm',
  PaymentTerm = 'Campaign.VIEW.paymentTerm',
  Budget = 'Campaign.VIEW.budget',
  DeliveryContact = 'Campaign.VIEW.deliveryContact',
  DeliveryMethod = 'Campaign.VIEW.deliveryMethod',
  DeliveryDays = 'Campaign.VIEW.deliveryDays',
  CustomerSuccessManager = 'Campaign.VIEW.customerSuccessManager',
  CustomerSuccessRep = 'Campaign.VIEW.customerSuccessRep',
  OperationsManager = 'Campaign.VIEW.operationsManager',
  QaManager = 'Campaign.VIEW.qaManager',
  QaTeamLeader = 'Campaign.VIEW.qaTeamLeader',
  DeliveryManager = 'Campaign.VIEW.deliveryManager',
  MisTeamLeader = 'Campaign.VIEW.misTeamLeader',
  CcdTeamLeader = 'Campaign.VIEW.ccdTeamLeader',
  AssignedTo = 'Campaign.VIEW.assignedTo',
  ActualStartDate = 'Campaign.VIEW.actualStartDate',
  ActualEndDate = 'Campaign.VIEW.actualEndDate',
  Status = 'Campaign.VIEW.status',

  Booked = 'Campaign.VIEW.booked',
  WaitingToGoLive = 'Campaign.VIEW.waitingToGoLive',
  Live = 'Campaign.VIEW.live',
  Paused = 'Campaign.VIEW.paused',
  Cancelled = 'Campaign.VIEW.cancelled',
  Delivered = 'Campaign.VIEW.delivered',
  Invoiced = 'Campaign.VIEW.invoiced',
  Paid = 'Campaign.VIEW.paid',

  AllCampaigns = 'Campaign.VIEW.all',
  CampaignsAssignedToMe = 'Campaign.VIEW.assignedToMe',
}

export enum EditCampaignPermissions {
  MarketerId = 'Campaign.EDIT.marketerId',
  Marketer = 'Campaign.EDIT.marketer',
  CampaignName = 'Campaign.EDIT.campaignName',
  CampaignId = 'Campaign.EDIT.campaignId',
  IoNumber = 'Campaign.EDIT.ioNumber',
  UploadIoFile = 'Campaign.EDIT.ioFileId',
  CampaignDescription = 'Campaign.EDIT.campaignDescription',
  SalesforceOpportunityId = 'Campaign.EDIT.salesforceOpportunityId',
  SalesforceOpportunityName = 'Campaign.EDIT.salesforceOpportunityName',
  SalesforceOpportunityLink = 'Campaign.EDIT.salesforceOpportunityLink',
  BillingSystemReferenceId = 'Campaign.EDIT.billingSystemReferenceId',
  OpportunityCloseDate = 'Campaign.EDIT.opportunityCloseDate',
  RetainerContract = 'Campaign.EDIT.retainerContract',
  BookedRevenue = 'Campaign.EDIT.bookedRevenue',
  CampaignGoals = 'Campaign.EDIT.campaignGoals',
  GoalDescription = 'Campaign.EDIT.goalDescription',
  TargetEndDate = 'Campaign.EDIT.targetEndDate',
  TargetStartDate = 'Campaign.EDIT.targetStartDate',
  InvoicingTerm = 'Campaign.EDIT.invoicingTerm',
  PaymentTerm = 'Campaign.EDIT.paymentTerm',
  Budget = 'Campaign.EDIT.budget',
  DeliveryContact = 'Campaign.EDIT.deliveryContact',
  DeliveryMethod = 'Campaign.EDIT.deliveryMethod',
  DeliveryDays = 'Campaign.EDIT.deliveryDays',
  CustomerSuccessManager = 'Campaign.EDIT.customerSuccessManager',
  CustomerSuccessRep = 'Campaign.EDIT.customerSuccessRep',
  OperationsManager = 'Campaign.EDIT.operationsManager',
  QaManager = 'Campaign.EDIT.qaManager',
  QaTeamLeader = 'Campaign.EDIT.qaTeamLeader',
  DeliveryManager = 'Campaign.EDIT.deliveryManager',
  MisTeamLeader = 'Campaign.EDIT.misTeamLeader',
  CcdTeamLeader = 'Campaign.EDIT.ccdTeamLeader',
  AssignedTo = 'Campaign.EDIT.assignedTo',
  ActualStartDate = 'Campaign.EDIT.actualStartDate',
  ActualEndDate = 'Campaign.EDIT.actualEndDate',
  Status = 'Campaign.EDIT.status',
}

export enum CreateCampaignPermissions {
  MarketerId = 'Campaign.CREATE.marketerId',
  Marketer = 'Campaign.CREATE.marketer',
  CampaignName = 'Campaign.CREATE.campaignName',
  CampaignId = 'Campaign.CREATE.campaignId',
  IoNumber = 'Campaign.CREATE.ioNumber',
  UploadIoFile = 'Campaign.CREATE.ioFileId',
  CampaignDescription = 'Campaign.CREATE.campaignDescription',
  SalesforceOpportunityId = 'Campaign.CREATE.salesforceOpportunityId',
  SalesforceOpportunityName = 'Campaign.CREATE.salesforceOpportunityName',
  SalesforceOpportunityLink = 'Campaign.CREATE.salesforceOpportunityLink',
  BillingSystemReferenceId = 'Campaign.CREATE.billingSystemReferenceId',
  OpportunityCloseDate = 'Campaign.CREATE.opportunityCloseDate',
  RetainerContract = 'Campaign.CREATE.retainerContract',
  BookedRevenue = 'Campaign.CREATE.bookedRevenue',
  GoalDescription = 'Campaign.CREATE.goalDescription',
  CampaignGoals = 'Campaign.CREATE.campaignGoals',
  TargetEndDate = 'Campaign.CREATE.targetEndDate',
  TargetStartDate = 'Campaign.CREATE.targetStartDate',
  InvoicingTerm = 'Campaign.CREATE.invoicingTerm',
  PaymentTerm = 'Campaign.CREATE.paymentTerm',
  Budget = 'Campaign.CREATE.budget',
  DeliveryContact = 'Campaign.CREATE.deliveryContact',
  DeliveryMethod = 'Campaign.CREATE.deliveryMethod',
  DeliveryDays = 'Campaign.CREATE.deliveryDays',
  CustomerSuccessManager = 'Campaign.CREATE.customerSuccessManager',
  CustomerSuccessRep = 'Campaign.CREATE.customerSuccessRep',
  OperationsManager = 'Campaign.CREATE.operationsManager',
  QaManager = 'Campaign.CREATE.qaManager',
  QaTeamLeader = 'Campaign.CREATE.qaTeamLeader',
  DeliveryManager = 'Campaign.CREATE.deliveryManager',
  MisTeamLeader = 'Campaign.CREATE.misTeamLeader',
  CcdTeamLeader = 'Campaign.CREATE.ccdTeamLeader',
  AssignedTo = 'Campaign.CREATE.assignedTo',
  ActualStartDate = 'Campaign.CREATE.actualStartDate',
  ActualEndDate = 'Campaign.CREATE.actualEndDate',
  Status = 'Campaign.CREATE.status',
}

export enum CampaignActionsEnum {
  View = 'Campaign.VIEW',
  Edit = 'Campaign.EDIT',
  Create = 'Campaign.CREATE',
}
