export enum HighlightedActionWords {
  VIEW = 'view',
  DOWNLOAD = 'download',
  EDIT = 'edit',
  CREATE = 'create',
  CLONE = 'clone',
  UPDATE = 'update',
  UPLOAD = 'upload',
  TRANSFORM_AND_EXPORT = 'transform & export',
  SCHEDULE_DELIVERY = 'schedule delivery',
  FILTER_LEADS_BY_VALIDATION_STATUS = 'filter leads by validation status',
  VALIDATE = 'validate',
  ACCESS_LEAD_REVIEW = 'access leads review',
  MARK = 'mark',
  ADD = 'add',
  REJECT = 'reject',
  PUBLISH = 'publish',
  ARCHIVE = 'archive',
  RETURN = 'return',
}
