export enum PermissionsGroupName {
  FIELDS = 'Fields',
  STATUS = 'Status',
  STATUSES = 'statuses',
  VIEW_DASHBOARD = 'View Dashboard',
  VIEW_CLIENT = 'View Client',
  EDIT_CLIENT = 'Edit Client',
  CREATE_CLIENT = 'Create Client',
  EDIT_LINE_ITEM = 'Edit Line Item',
  CREATE_LINE_ITEM = 'Create Line Item',
  VIEW_LINE_ITEM = 'View Line Item',
  LIST_VIEW_PRESETS = 'List View Presets',
  LINE_ITEM_STATUS = 'Line Item Status',
  UDPATE_LINE_ITEM_STATUS = 'Update Line Item Status',
  UPDATE_LEAD = 'Update Lead',
  UPLOAD_NEW_LEADS = 'Upload New Leads',
  EDIT_CAMPAIGN = 'Edit Campaign',
  CREATE_CAMPAIGN = 'Create Campaign',
  VIEW_CAMPAIGN = 'View Campaign',
  VIEW_JOBS = 'View Jobs',
}
